site_name: 52Pi Docs 
nav:
  - HOME: 'index.md'
  - KZ-0083:
    - Raspberry Pi Pico 2 WH Starter Kit: 'md/kz-0083/getting-start.md' 
    - Project 1: 'md/kz-0083/project1.md'
    - Project 2: 'md/kz-0083/project2.md'
    - Project 3: 'md/kz-0083/project3.md'
    - Project 4: 'md/kz-0083/project4.md'
    - Project 5: 'md/kz-0083/project5.md'
    - Project 6: 'md/kz-0083/project6.md'
    - Project 7: 'md/kz-0083/project7.md'
    - Project 8: 'md/kz-0083/project8.md'
    - Project 9: 'md/kz-0083/project9.md'

  - KZ-0084:
    - Ultimate Starter Kit for Raspberry Pi Pico 2 WH: 'md/kz-0084/projects.md'

  - KZ-0054:
    - Cloud Ready Starter Kit for Arduino UNO R4 WiFi: 'md/kz-0054/whatinkit.md'

  - KZ-0069:
    - Plant Watering Kit: 'md/kz-0069/package_includes.md'
    - Getting Start: 'md/kz-0069/getting_start.md'
    - Basic Usage 1: 'md/kz-0069/basic_usage_1.md'
    - Basic Usage 2: 'md/kz-0069/basic_usage_2.md'
    - Basic Usage 3: 'md/kz-0069/basic_usage_3.md'
    - Basic Usage 4: 'md/kz-0069/basic_usage_4.md'
    - Basic Usage 5: 'md/kz-0069/basic_usage_5.md'
    - Basic Usage 6: 'md/kz-0069/basic_usage_6.md'
    - Networking: 'md/kz-0069/network_configuration.md'
    - MQTT broker: 'md/kz-0069/mosquitto_mqtt_broker.md'
    - HomeAssistant: 'md/kz-0069/home_assistant.md'
    - Arduino Cloud: 'md/kz-0069/arduino_cloud.md'

  - KZ-0073:
    - Education Starter Kit: 'md/kz-0073/whatinkit.md'
    - Preparation: 'md/kz-0073/preparation.md'
    - Getting Start : 'md/kz-0073/getting-start.md'
    - Project 1: 'md/kz-0073/arduino/p1.md'
    - Project 2: 'md/kz-0073/arduino/p2.md'
    - Project 3: 'md/kz-0073/arduino/p3.md'
    - Project 4: 'md/kz-0073/arduino/p4.md'
    - Project 5: 'md/kz-0073/arduino/p5.md'
    - Project 6: 'md/kz-0073/arduino/p6.md'
    - Project 7: 'md/kz-0073/arduino/p7.md'
    - Project 8: 'md/kz-0073/arduino/p8.md'
    - Project 9: 'md/kz-0073/arduino/p9.md'
    - Project 10: 'md/kz-0073/arduino/p10.md'

  - KZ-0077:
    - Student Starter Kit: 'md/kz-0077/student_starter_kit.md'

  - KZ-0068:
    - Universal Sensor Kit(TBD): 'md/kz-0068/whatinkit.md'
    - Preparation: 'md/kz-0068/preparation.md'
    - Getting Start : 'md/kz-0068/getting-start.md'
    - Project 1: 'md/kz-0068/arduino/p1.md'
    - Project 2: 'md/kz-0068/arduino/p2.md'
    - Project 3: 'md/kz-0068/arduino/p3.md'
    - Project 4: 'md/kz-0068/arduino/p4.md'
    - Project 5: 'md/kz-0068/arduino/p5.md'
    - Project 6: 'md/kz-0068/arduino/p6.md'
    - Project 7: 'md/kz-0068/arduino/p7.md'
    - Project 8: 'md/kz-0068/arduino/p8.md'
    - Project 9: 'md/kz-0068/arduino/p9.md'
    - Project 10: 'md/kz-0068/arduino/p10.md'
  - Contact: 
    - E-Mail: 'md/contact.md'

theme: readthedocs

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html

plugins:
  - mkdocs-video
